Month 7/step 2
daryamakavchik/react-burger pull request #2
Opened 2022-05-30 23:21 UTC by daryamakavchik

2022-05-31 14:57 UTC, kyzinatra commented on src/components/app/app.jsx
> +      .catch((e) => {
Надо исправить: Стоит добавить проверку успешности выполнения с помощью `res.ok` так как `catch` ловит только ошибки в самом запросе, но если сервер вернет в кримеру ошибку `404`, то ее `catch` не поймает.

[Подробнее:](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch) ([https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch](https://developer.mozilla.org/ru/docs/Web/API/Fetch_API/Using_Fetch))

2022-05-31 14:58 UTC, kyzinatra commented on src/components/app/app.jsx
> +      .then((obj) => setState({ ...state, data: obj.data, isLoading: false }))
Можно лучше: круто было бы вынести `fetch` и саму проверку запроса в отдельный файл в `utils` а тут вызывать эту функцию и использовать setState

2022-05-31 14:59 UTC, kyzinatra commented on src/components/app/app.jsx
> +    data: [],
Нужно исправить: стоит дать более конкретное название переменной

2022-05-31 15:00 UTC, kyzinatra commented on src/components/app/app.jsx
> +    getIngredients();
Можно лучше: вместо того, чтобы использовать `React.useEffect` можно импортировать сразу `useEffect`

```js
import React, {useEffect, useState} from "react"; 
```

2022-05-31 15:00 UTC, kyzinatra commented on src/components/app/app.jsx
> +          {!state.isLoading && !state.hasError && (
Отлично! Круто что вы обрабатываете ошибки

2022-05-31 15:01 UTC, kyzinatra commented on src/components/app-header/app-header.jsx
> +            Конструктор
**Надо исправить**

Оберните иконку и текст в ссылку в шапке в ссылку `<a href="#">`

Например

`<a href="#" class="......">
 Конструктор 
</a>`

В следующих спринтах вместо ссылки будет компонент Link из библиотеки react router, а пока сделайте просто ссылкой

2022-05-31 15:01 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
Отлично! Круто что вы реализовали прокрутку

2022-05-31 15:05 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +  _id: PropTypes.string.isRequired,
Можно лучше: будет круто, если вы вынесете обьявление этого типа в отдельный файл в `utils/` и будете его импортировать сюда, а также пропишите `.isRequire` для самого массива (указать, что он точно будет) и для элемента из `PropTypes.shape`, чтобы показать, что массив не пустой

2022-05-31 15:07 UTC, kyzinatra commented on src/components/ingredients-category/ingredients-category.jsx
> +        ))}
Можно лучше: будет круто, если добавить `cursor: pointer` к стилю карточки

2022-05-31 15:08 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +              <ConstructorElement
Можно лучше: лучше убрать пустое пространство `{" "}`, если нужны отступы, то лучше задать их в `css`

2022-05-31 15:10 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Надо исправить: `Modal` должен быть компонентом. Лучше сразу создать компонент `Modal` и не использовать прослойку в виде функции, а функцию `setOpen`, лучше передавать сверху в `Modal` как пропс `onClose` к примеру

2022-05-31 15:16 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +          price={data[0].price}
Надо исправить: Название булки также должны браться из входящих данных так как в будущем эта информация будет меняться. Сделать это можно с помощью `.find` к примеру. Найти булку и использовать ее

2022-05-31 15:21 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- Добавить проверку `res.ok`
- Исправить абстрактное название `setState`
- обернуть ссылки в навигации в `<a>`
- Использовать `Modal` как компонент, без прослойки ввиде функции
- Брать название булки из входящих данных

Можно лучше:

- Убрать лишние `{" "}`
- Немного доработать верстку
- Стилизовать скролл у компонентов
<img width="77" alt="image" src="https://user-images.githubusercontent.com/51288221/171204183-0faab35f-19ae-4c59-b48e-9b733f40bc60.png">
- Стоит убрать верхний отступ у шапки
<img width="162" alt="image" src="https://user-images.githubusercontent.com/51288221/171204347-74d5591b-0942-4d9e-831a-1019201f626c.png">
<img width="162" alt="image" src="https://user-images.githubusercontent.com/51288221/171204420-5c496077-d874-4de2-8dff-a3cbd07e1b88.png">
- Использовать `isRequired`


Что понравилось:

- Хорошая структура кода
- Сама техническая часть реалихована хорошо. Все технологии применены правильно

Обратите внимание, что работа принимается только после исправления всех `«Надо исправить»`.

2022-05-31 20:10 UTC, daryamakavchik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
`element.scrollIntoView({ behavior: "smooth" });`:

https://user-images.githubusercontent.com/90967822/171275428-3848d080-bdaa-4dc6-b623-ca19346930f2.mov

`element.scrollIntoView({ behavior: "smooth", block: "nearest" });`:

https://user-images.githubusercontent.com/90967822/171275620-b0d93fa9-119d-4d7f-a9a2-13f56fd24048.mov

```
    containerRef.current.scroll({
      behavior: "smooth",
      top: ref.current.offsetTop - containerRef.current.offsetTop - 40,
    });
```

https://user-images.githubusercontent.com/90967822/171276007-a2ee4b04-a81d-4082-92e7-7575485f514d.mov

2022-05-31 20:19 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
Так ведь `Modal` и так компонент, или нет? Почему функцию `setOpen` лучше передавать сверху?

2022-05-31 20:28 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Философия реакт заключается в том, что мы используем структуру дерева и потомки не имеют доступа к родителям. Используя эту прослойку вы нарушаете эту философию.  (Кстати по тому же принципу нельзя с помощью css селекторов выбрать родителя, только потомка) 
Поступая так вы рискуете в будущем получить сложности в расширении кодовой базы и просто ломаете всё оптимизации и предположения реакта

2022-05-31 20:31 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
https://ru.reactjs.org/docs/thinking-in-react.html
Подробнее как  реакт предполагает построение приложений
(Стоит в большинстве случаев соблюдать эти предположения так как на них строятся сложные алгоритмы внутри реакт) 
+ как бонус другим разработчикам сложно понять такой код. В нём придётся покопаться прежде чем понять что в нём происходит

2022-05-31 20:33 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
Как нравится больше :D. В этом плане я не критикую ваш метод

2022-05-31 20:43 UTC, daryamakavchik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
https://yandex-students.slack.com/archives/C02K2LN4DGE/p1653683004752049?thread_ts=1653673749.067649&cid=C02K2LN4DGE

<img width="381" alt="image" src="https://user-images.githubusercontent.com/90967822/171280930-ea6670c9-21ee-4470-b7cb-97b7e36d8ded.png">

Просто если ты пишешь что можно написать проще, то приведи пожалуйста пример как это сделать. А то странно получается что ты предлагаешь что-то, что не работает 🙂

2022-05-31 20:58 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
Такие вопросы стоит уточнять у наставника. Потому что он отвечает за это, но я представляю это так 
```jsx
const onTabClick = (tab) => {
    setCurrentTab(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <section className={styles.burger_ingredients}>
        <nav>
          <ul className={styles.menu}>
            <Tab
              value="buns"
              active={currentTab === "buns"}
              onClick={onTabClick}
            >
              Булки
            </Tab>
            <Tab
              value="mains"
              active={currentTab === "mains"}
              onClick={onTabClick}
            >
              Начинки
            </Tab>
... 
```

2022-05-31 20:59 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
Так как это нарушает философию реакта? То есть в функции `useModal` создаётся состояние и передаётся сверху в компонент `Modal`. А сам метод возвращает компонент и состояние к нему, насколько это сложно понять и как долго разработчикам придётся копаться прежде чем понять что в нём происходит 🙂 ?

То есть разберём пример:
```
export const useModal = () => {
  const [isOpen, setOpen] = useState(false);
  return [
    (props) =>
      isOpen ? (
        <Modal
          setOpen={setOpen}
          {...props}
        />
      ) : null,
    setOpen,
  ];
};

export default function BurgerIngredient(props) {
  const [Modal, setOpen] = useModal();

  return (
    <>
      <div className={styles.optioncard} onClick={() => setOpen(true)}>
        <img src={props.image} />
        <p className={styles.optiontext}>{props.name}</p>
      </div>
      <Modal title="Детали ингридиента">
        <IngredientsDetails {...props} />
      </Modal>
    </>
  );
}

```

и

```
export default function BurgerIngredient(props) {
  const [isOpen, setOpen] = useState(false);

  return (
    <>
      <div className={styles.optioncard} onClick={() => setOpen(true)}>
        <img src={props.image} />
        <p className={styles.optiontext}>{props.name}</p>
      </div>
      {isOpen && (
        <Modal setOpen={setOpen} title="Детали ингридиента">
          <IngredientsDetails {...props} />
        </Modal>
      )}
    </>
  );
}
```

Разница только в том что часть кода была вынесена в отдельную функцию, как это нарушает философию/ломает предположения реакта?

2022-05-31 21:10 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Ну 2 вариант как минимум выглядит проще. К тому же он гибче так как вы сами решаете как обрабатывать  закрытие модального окна. К тому же такое использование хуков приведёт к повторным пересчетам дерева. Так как мы каждый раз возвращаем из Хука новый для реакта Modal

2022-05-31 21:13 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Просто из личного опыта даже скажу, что это не самый надёжный способ добиться гибкости когда и на большой дистанции соблюдать каноничные подходы оказывается более эффективно

2022-05-31 21:14 UTC, daryamakavchik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
> Такие вопросы стоит уточнять у наставника. Потому что он отвечает за это, но я представляю это так
> 
> ```js
> const onTabClick = (tab) => {
>     setCurrentTab(tab);
>     const element = document.getElementById(tab);
>     if (element) element.scrollIntoView({ behavior: "smooth" });
>   };
> 
>   return (
>     <>
>       <section className={styles.burger_ingredients}>
>         <nav>
>           <ul className={styles.menu}>
>             <Tab
>               value="buns"
>               active={currentTab === "buns"}
>               onClick={onTabClick}
>             >
>               Булки
>             </Tab>
>             <Tab
>               value="mains"
>               active={currentTab === "mains"}
>               onClick={onTabClick}
>             >
>               Начинки
>             </Tab>
> ... 
> ```

Видео о том как это работает я уже прикрепила, а ты запускал и проверял как работает то что ты предлагаешь? Я только что проверила ещё раз и это работает в точности как на первом видео.

> Такие вопросы стоит уточнять у наставника.
Я понимаю, поэтому показала тебе его ответ и привела пример с тем как работает то что он предложил. Его вариант перестаёт работать для элементов которые уже отображаются на экране.

2022-05-31 21:18 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
Насколько большая разница в сложности этих двух вариантов?

```
export default function BurgerIngredient(props) {
  const [Modal, setOpen] = useModal();

  return (
    <>
      <div className={styles.optioncard} onClick={() => setOpen(true)}>
        <img src={props.image} />
        <p className={styles.optiontext}>{props.name}</p>
      </div>
      <Modal title="Детали ингридиента">
        <IngredientsDetails {...props} />
      </Modal>
    </>
  );
}
```

```
export default function BurgerIngredient(props) {
  const [isOpen, setOpen] = useState(false);

  return (
    <>
      <div className={styles.optioncard} onClick={() => setOpen(true)}>
        <img src={props.image} />
        <p className={styles.optiontext}>{props.name}</p>
      </div>
      {isOpen && (
        <Modal setOpen={setOpen} title="Детали ингридиента">
          <IngredientsDetails {...props} />
        </Modal>
      )}
    </>
  );
}
```

И всё таки как использование метода для объявления состояния нарушает филосифию/ломает предположения реакта? 🙂

2022-05-31 21:22 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
Нет, я не запускал этот код сам, но я уверен, что он должен работать. Опять же повторюсь, что мне нравится ваш вариант, я просто предложил альтернативу. Если у вас не получается добиться нужного поведения, то оставьте как было ничего страшного. 1 вариант более чем имеет право на жизнь

2022-05-31 21:28 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Давайте на секунду забудем, что это пользовательский хук. (Ведь это же обычная функция)) 
Вы из этой функции, которая возвращает компонент jsx возвращаете также и состояние для контроля поведения этого компонента. И используете его а родителе. Получается связка child -> parent

2022-05-31 21:29 UTC, daryamakavchik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
Так это не у меня не получается, у меня как раз получилось добиться нужного поведения с тем что я написала. Мне намного интереснее разобраться в том что ты предлагаешь, потому что то что ты написал не работает. Напиши пожалуйста как сделать так чтобы альтернативный вариант с `scrollIntoView` работал нормально. Согласись, странно же предлагать что то, что не работает? 🙂

2022-05-31 21:35 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
К сожалению я не вижу всей картины, не вижу кода в вашем редакторе, вашего браузера и всей картины. Так что сейчас непосредственно дать вам ответ на этот вопрос я не могу

2022-05-31 21:45 UTC, daryamakavchik commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
А ты можешь скинуть репозиторий с этим вариантом? Я бы посмотрела и разобралась сама тогда 👀

2022-05-31 21:52 UTC, kyzinatra commented on src/components/burger-ingredients/burger-ingredients.jsx
> +      behavior: "smooth",
К сожалению не могу( он приватный и только для ревьюеров

2022-05-31 22:02 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
А кто в этой связке child, а кто parent?

2022-05-31 22:03 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
Что то я совсем запуталась 😄

2022-06-01 20:56 UTC, kyzinatra commented
Поздравляю! Ваша работа принята.

Вы отлично потрудились.

Удачного дальнейшего обучения.

2022-06-02 00:42 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
@kyzinatra Ответь пожалуйста, мне очень интересно 🙂

2022-06-02 06:04 UTC, merged

2022-06-11 19:48 UTC, daryamakavchik commented on src/components/burger-constructor/burger-constructor.jsx
> +
@kyzinatra Данил, ну ты где там пропал? Я просто подумала раз ты уже даже такой пример привёл, то должно быть просто указать что из приведённого child, а что parent 🥲

2022-06-11 20:19 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Прости пожалуйста. Уведомления на почту не приходили да, конечно, смотри. В данном случае parent это тот компонент, который рендерит Modal,  то есть BurgerIngredient(props). 
А Modal это его потомок. Ваша реализация в виде Хука позволяет тому, кто рендерит компонент, независимо управлять его состоянием. 
То есть

BurgerIngreingt ренеит Modal при этом не передает никаких про псов ему. Реакт думает что раз так, то грубо говоря этот компонент может менять только сам себя и не зависит от внешних пропсов.

Давай попробуем разобрать вот такой пример, который должно быть покажется тебе странным, но по большому счету это всё одно и тоже

```js
let c;
const a = () => {
const [state, useState] = useState() 
c = useState;
return (...) 
}

const b = () => {
useEffect(() =>{
c(2983) }, []) 
return (<a/>) 
}
```

Согласитесь это выглядит очень странно и не естественно. Потому что это нарушает ту логику с которой react разрабатывал компоненты и хуки для них

2022-06-11 20:21 UTC, kyzinatra commented on src/components/burger-constructor/burger-constructor.jsx
> +
Надеюсь стало понятнее)